variable "env" {
  description = "Environment name (prod, staging)"
  type        = string
}

variable "common_tags" {
  description = "Tags applied to every resource"
  type        = map(string)
}

variable "db_password" {
  description = "RDS master password (generated by env-level random_password)"
  type        = string
  sensitive   = true
}
